### PR TITLE
Updated Aditya and Swanand's workshop description

### PR DESCRIPTION
**Pull request by swanandp**
Also minor formatting updates.

### CODE REVIEW

**Comment by swanandp** [comment]
Damn, that was fast. I was about to say, don't merge it yet.

**Comment by prathamesh-sonpatki** [comment]
🤘

**Comment by swanandp** [comment]
Can you add me as a contributor on this, will make a few minor changes, like add anchor links.

**Comment by prathamesh-sonpatki** [comment]
Done, thanks

**Comment by swanandp** [comment]
Do we have auto deploy? If not, please do a deployment.

**Comment by prathamesh-sonpatki** [comment]
It gets auto deployed via github pages

**Pull request merged**
