### PR TITLE
UI fixes for sponsors section

### PR DESCRIPTION
**Pull request by vishwasja**
Added UI fixes for the sponsors section.

### CODE REVIEW

**Comment by prathamesh-sonpatki** [comment]
@anildigital Please review.

**Comment by anildigital** [comment]
@vishwasja Nice

A simple change needed

Gojek logo looks stretched.

screenshot 2016-07-15 22 25 02

**Comment by anildigital** [comment]
@vishwasja 
screenshot 2016-07-15 22 47 12 

Oogway logo is also stretched. Somehow RedPanthers logo look big.

Could you make logo sizes reduced by percentages as per sponsorship type? Check current production/live website for logo sizes. 

Also you have old copy of Gojek logo than one in live website.

**Comment by vishwasja** [comment]
@anildigital : updated, please have a look.

**Pull request closed without merging**
